"""Generate every LaTeX table in paper/tables/ from the committed result artifacts.

Nothing here is transcribed by hand except the cell-identity table, whose rows are copied
from the run manifests under Tests/ (git-ignored) and the preregistration execution logs.
Every numeric table is read from Experiments/*.json so the manuscript cannot drift from the
frozen artifacts.

Usage (from the repository root):
    python paper/build_tables.py
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXP = os.path.join(ROOT, "Experiments")
OUT = os.path.join(ROOT, "paper", "tables")
SIX_CELL_BRIDGE = os.path.join(ROOT, "paper", "data",
                               "churilov_bridge_analysis_six_cell_eac1434.json")

NAMES = {
    "claude-opus-5": "Claude Opus 5",
    "gpt-5.2-2025-12-11": "GPT-5.2",
    "gpt-oss:20b": "gpt-oss 20B",
    "grok-4.6": "Grok 4.6",
    "deepseek-coder-v2:16b": "DeepSeek Coder V2 16B",
    "deepseek-v4-flash": "DeepSeek V4 Flash",
    "qwen3.5:cloud": "Qwen 3.5 Cloud",
    "kimi-k2.7-code:cloud": "Kimi K2.7 Code",
    "kimi-k3:cloud": "Kimi K3",
}
SHORT = {
    "claude-opus-5": "Opus 5",
    "gpt-5.2-2025-12-11": "GPT-5.2",
    "gpt-oss:20b": "gpt-oss",
    "grok-4.6": "Grok 4.6",
    "deepseek-coder-v2:16b": "DS Coder V2",
    "deepseek-v4-flash": "DS V4 Flash",
    "qwen3.5:cloud": "Qwen 3.5",
    "kimi-k2.7-code:cloud": "Kimi K2.7",
    "kimi-k3:cloud": "Kimi K3",
}
TRACK_B = ["claude-opus-5", "gpt-5.2-2025-12-11", "gpt-oss:20b", "grok-4.6",
           "deepseek-coder-v2:16b", "deepseek-v4-flash"]
EXT = ["qwen3.5:cloud", "kimi-k2.7-code:cloud", "kimi-k3:cloud"]
ALL9 = TRACK_B + EXT


def load(name):
    with open(os.path.join(EXP, name), encoding="utf-8") as handle:
        return json.load(handle)


def pct(x, d=2):
    return "--" if x is None else f"{x:.{d}f}"


def ci(pair, d=2):
    return f"{pair[0]:.{d}f}--{pair[1]:.{d}f}"


def num(x):
    return f"{int(x):,}"


def pfloor(p, floor):
    return f"$\\leq${floor:.6f}".rstrip("0") if p <= floor + 1e-12 else f"{p:.4f}"


def tex_escape(text):
    return (str(text).replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
            .replace("#", "\\#"))


def write(name, body):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("% Generated by paper/build_tables.py -- do not edit by hand.\n")
        handle.write(body)
    print("wrote", os.path.relpath(path, ROOT))


def table(env, cols, header, rows, caption, label, size="\\small", notes=None,
          placement="t", colsep="3pt"):
    lines = [f"\\begin{{{env}}}[{placement}]", "\\centering", size,
             f"\\setlength{{\\tabcolsep}}{{{colsep}}}",
             "\\begin{adjustbox}{max width=\\linewidth}",
             f"\\begin{{tabular}}{{{cols}}}", "\\toprule", header + " \\\\", "\\midrule"]
    for row in rows:
        if isinstance(row, (list, tuple)):
            lines.append(" & ".join(row) + " \\\\")
        elif row.startswith(r"\midrule"):
            lines.append(row)
        else:
            lines.append(row + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{adjustbox}"]
    if notes:
        lines.append("\\par\\vspace{2pt}\\begin{minipage}{\\linewidth}\\footnotesize " +
                     notes + "\\end{minipage}")
    lines += [f"\\caption{{{caption}}}", f"\\label{{{label}}}", f"\\end{{{env}}}", ""]
    return "\n".join(lines)


# ----------------------------------------------------------------------------------
# Table 1: cells, identities, protocol settings (transcribed from run manifests and
# preregistration execution logs; see paper/README.md).
# ----------------------------------------------------------------------------------
def build_cells():
    rows = [
        ["CodeLlama 7B Instruct", "A", "\\texttt{codellama:7b-instruct}; digest \\texttt{8fdf8f75\\ldots}",
         "7B, Q4\\_0 GGUF", "n/a", "all three", "2048 / 64", "2026-08-13"],
        ["DeepSeek Coder 6.7B Instruct", "A", "\\texttt{deepseek-coder:6.7b-instruct}; digest \\texttt{ce298d98\\ldots}",
         "7B, Q4\\_0 GGUF", "n/a", "all three", "2048 / 64", "2026-08-13"],
        ["Claude Opus 5", "B", "\\texttt{claude-opus-5} (Anthropic API)", "hosted",
         "thinking disabled", "T, top-$k$, top-$p$ rejected, dropped", "4096 / 2048", "2026-08-13"],
        ["GPT-5.2", "B", "\\texttt{gpt-5.2-2025-12-11} (OpenAI API)", "hosted",
         "reasoning effort \\texttt{none}", "top-$k$ unsupported, dropped", "4096 / 2048", "2026-08-13"],
        ["gpt-oss 20B", "B", "\\texttt{gpt-oss:20b}; digest \\texttt{17052f91\\ldots}",
         "20.9B, MXFP4 GGUF", "native reasoning retained", "all three", "4096 / 2048", "2026-08-13"],
        ["Grok 4.6", "B", "\\texttt{grok-4.6} (xAI API)", "hosted", "default",
         "top-$k$ unsupported, dropped", "4096 / 2048", "2026-08-13"],
        ["DeepSeek Coder V2 16B", "B", "\\texttt{deepseek-coder-v2:16b}; digest \\texttt{63fb193b\\ldots}",
         "15.7B, Q4\\_0 GGUF", "n/a", "all three", "4096 / 2048", "2026-08-13$^{\\dagger}$"],
        ["DeepSeek V4 Flash", "B", "\\texttt{deepseek-v4-flash:cloud} (Ollama Cloud)", "hosted",
         "\\texttt{think:false}", "all three", "4096 / 2048", "2026-08-13"],
        ["Qwen 3.5 Cloud", "C", "\\texttt{qwen3.5:cloud}, served \\texttt{qwen3.5}", "397B, BF16",
         "\\texttt{think:false}", "all three", "4096 / 2048", "2026-08-19"],
        ["Kimi K2.7 Code", "C", "\\texttt{kimi-k2.7-code:cloud}, served \\texttt{kimi-k2.7-code}", "1.042T, INT4",
         "\\texttt{think:false}", "all three", "4096 / 2048", "2026-08-19"],
        ["Kimi K3", "D", "\\texttt{kimi-k3:cloud}, served \\texttt{kimi-k3}", "2.812T, MXFP4",
         "\\texttt{think:false}", "all three", "4096 / 2048", "2026-08-25"],
    ]
    notes = ("Tracks: A = historical replication (paper protocol, three generation seeds); "
             "B = Campaign~4 modern benchmark; C = separately preregistered Ollama Cloud extension; "
             "D = Kimi K3 successor cell. Sampling: temperature 0.7 (code) / 0.01 (package queries), "
             "top-$k$ 20, top-$p$ 0.9 where the provider accepts them. Caps are code / package-query "
             "response tokens. Every hosted cell records the served model id echoed in each response; "
             "local cells record the Ollama digest, quantization, and server version. "
             "$^{\\dagger}$Four resumed invocations with mixed worker counts (1, 2) and context settings "
             "(12,288; 16,384; 32,768); the digest was stable throughout.")
    return table("table*", "@{}p{2.1cm}cp{4.1cm}p{1.8cm}p{2.2cm}p{2.4cm}p{1.2cm}p{1.5cm}@{}",
                 "Cell & Track & Identity & Size, quant. & Reasoning setting & Sampling sent & Caps & Date",
                 rows, "Model cells, exact identities, and protocol settings.", "tab:cells",
                 size="\\scriptsize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 2: parser validation and Track B audit.
# ----------------------------------------------------------------------------------
def build_parser():
    v = load("parser_v2_validation.json")
    a = load("campaign4_post_analysis.json")["parser_track_b_audit"]
    rd = v["recall_decomposition_corrected"]
    rows = [
        ["\\multicolumn{2}{@{}l}{\\textit{Initial validation sample (pre-campaign runs; labels signed 2026-08-13)}}"],
        ["Records", num(v["sample_size"])],
        ["Response-status accuracy",
         f"{v['response_status_accuracy']['pct']:.1f}\\% ({v['response_status_accuracy']['agree']}/{v['sample_size']})"],
        ["Status errors (root cause)", f"{v['parser_errors']['count']} (wrappers around an entire comma list)"],
        ["Extraction precision", "100\\% (no incorrectly extracted token)"],
        ["Grammar-valid occurrence recall",
         f"{rd['grammar_valid_recall_pct']:.2f}\\% ({rd['extracted_from_grammar_valid']}/"
         f"{rd['extracted_from_grammar_valid'] + rd['missed_parser_defect_wrappers']})"],
        ["End-to-end semantic recall", f"{rd['end_to_end_semantic_recall_pct']:.2f}\\%"],
        ["\\quad after the wrapper fix (v2.1 candidate)", f"{rd['end_to_end_after_wrapper_fix_pct']:.2f}\\%"],
        ["Occurrences withheld by deliberate abstention", num(rd["missed_deliberate_grammar_abstention"])],
        ["Records with recommendations inside malformed text",
         num(v["recall_cost_of_strict_grammar"]["records_with_recommendations_inside_malformed"])],
        ["\\midrule"],
        ["\\multicolumn{2}{@{}l}{\\textit{Post-campaign Track B audit (hosted formats; 20 random + 10 challenge per cell)}}"],
        ["Records", num(a["sample_size"])],
        ["Frozen-contract status agreement", f"{a['status_accuracy_pct']:.0f}\\% ({a['by_selection_group']['random_core']['status_agree'] + a['by_selection_group']['challenge']['status_agree']}/{a['sample_size']})"],
        ["Exact extraction agreement", f"{a['exact_extraction_agreement_pct']:.0f}\\%"],
        ["Random core / challenge set",
         f"{a['by_selection_group']['random_core']['status_agree']}/{a['by_selection_group']['random_core']['n']} / "
         f"{a['by_selection_group']['challenge']['status_agree']}/{a['by_selection_group']['challenge']['n']}"],
        ["Semantic anomalies annotated",
         f"{a['semantic_anomalies']['no_package_prose']} no-package prose; "
         f"{a['semantic_anomalies']['literal_trailing_eos_transport_marker']} literal \\texttt{{<|eos|>}} markers; "
         f"{a['semantic_anomalies']['collapsed_no_package_sentinel']} collapsed no-package sentinel"],
    ]
    fmt = []
    for r in rows:
        fmt.append(r[0] if len(r) == 1 else r)
    notes = ("Both reviews were delegated to a second AI system (OpenAI Codex) at maintainer direction; "
             "no human read every record. Contract agreement validates the frozen grammar, not semantic "
             "validity of every extracted token.")
    return table("table", "@{}p{4.4cm}>{\\raggedleft\\arraybackslash}p{3.7cm}@{}", "Quantity & Value", fmt,
                 "Parser v2 validation and the Track B frozen-contract audit.", "tab:parser",
                 size="\\footnotesize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 3: Track A seed-level replication.
# ----------------------------------------------------------------------------------
def build_tracka():
    t = load("campaign4_results.json")["track_a"]
    rows = []
    for model, label in (("codellama:7b-instruct", "CodeLlama 7B"),
                         ("deepseek-coder:6.7b-instruct", "DeepSeek Coder 6.7B")):
        cell = t[model]
        paper = cell["paper"]["rate_pct"]
        for i, seed in enumerate(cell["seeds"], 1):
            g = seed["generic_parser"]
            st = seed["parser_v2_statuses"]
            caps = sum(seed["cap_hits_per_phase"].values())
            fam = seed.get("family_parser")
            rows.append([
                label if i == 1 else "", f"{paper:.2f}" if i == 1 else "", str(100 + i),
                f"{g['rate_pct']:.2f}", ci(g["cluster_ci"]), "yes" if g["ci_contains_paper"] else "no",
                f"{fam['rate_pct']:.2f}" if fam else "--", ci(fam["cluster_ci"]) if fam else "--",
                ("yes" if fam["ci_contains_paper"] else "no") if fam else "--",
                f"{100 * st['malformed'] / 1600:.1f}", num(caps),
            ])
        rows.append(["\\quad seed mean", "", "", f"{cell['seed_mean_pct']:.2f}", "", "",
                     f"{cell['family_seed_mean_pct']:.2f}" if "family_seed_mean_pct" in cell else "--",
                     "", "", "", ""])
    notes = ("Paper protocol exactly (caps 2048/64, temperature 0.7/0.01, top-$k$ 20, top-$p$ 0.9), one "
             "frozen 200-prompt-per-dataset subset, three independent generation seeds per model, frozen "
             "2024-01-10 registry. Intervals are dataset-stratified prompt-cluster bootstraps. The generic parser "
             "is the historical parser for CodeLlama; the DeepSeek family parser is the historical parser for "
             "DeepSeek and therefore the acceptance condition. Parser~v2 malformed shares are diagnostic; the "
             "64-token cap truncates DeepSeek package queries so often that most of its responses fail the strict "
             "grammar. Cap hits are summed over all twelve phases.")
    return table("table*", "@{}llrrlcrlcrr@{}",
                 "Model & Paper (\\%) & Seed & Generic (\\%) & 95\\% CI & $\\ni$ paper & Family (\\%) & 95\\% CI & $\\ni$ paper & v2 malformed (\\%) & Cap hits",
                 rows, "Track A: seed-level replication estimates against the published values.",
                 "tab:tracka", size="\\scriptsize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 4: Track B primary outcomes.
# ----------------------------------------------------------------------------------
def build_trackb():
    r = load("campaign4_results.json")["track_b"]
    p = load("campaign4_post_analysis.json")["track_b"]
    rows = []
    for m in TRACK_B:
        c, q = r[m], p[m]
        rows.append([NAMES[m], f"{q['unregistered_rate_pct']:.2f}", ci(q["unregistered_rate_cluster_ci"]),
                     f"{c['prompt_level_risk_pct']:.1f}", f"{q['malformed_rate_pct']:.2f}",
                     f"{q['empty_rate_pct']:.2f}", f"{c['packages_per_prompt']:.2f}",
                     num(q["parsed_package_occurrences"]), num(c["unique_unregistered_names"]),
                     f"{q['tail']['top3_response_share_pct']:.1f}", f"{q['tail']['leave_top3_rate_pct']:.2f}"])
    notes = ("Rate = unregistered-PyPI recommendation occurrences / Parser~v2-accepted package occurrences "
             "(absent from both the 2024-01-10 and 2026-08-12 snapshots and not a standard-library module). "
             "Intervals: 50,000-replicate dataset-stratified prompt-cluster percentile bootstrap. Prompt risk = "
             "share of the 800 prompts with at least one unregistered recommendation. Top-3 share = share of "
             "unregistered occurrences supplied by the three worst responses; leave-3 = rate after removing them "
             "(a concentration diagnostic, not an alternative estimand). $n = 1{,}600$ package responses per cell.")
    return table("table*", "@{}lrlrrrrrrrr@{}",
                 "Model & Rate (\\%) & 95\\% CI & Risk (\\%) & Malf.\\ (\\%) & Empty (\\%) & Pkgs/prompt & Parsed & Unique & Top-3 (\\%) & Leave-3 (\\%)",
                 rows, "Track B primary outcomes with response coverage and concentration.", "tab:trackb",
                 size="\\scriptsize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 5: paired comparisons, both Holm conventions.
# ----------------------------------------------------------------------------------
def pair_label(pair):
    a, b = pair.split(" vs ")
    return f"{SHORT[a]} vs.\\ {SHORT[b]}"


def build_paired():
    ps = load("campaign4_post_analysis.json")["paired_sensitivity"]
    ps = sorted(ps, key=lambda c: c["bootstrap_tail_holm_p"])
    rows = []
    for c in ps:
        rows.append([pair_label(c["pair"]), f"{c['observed_diff_pp']:.2f}", ci(c["percentile_ci"]),
                     f"{c['bootstrap_tail_holm_p']:.4f}", "yes" if c["bootstrap_tail_holm_significant_05"] else "no",
                     f"{c['recentered_null_holm_p']:.4f}", "yes" if c["recentered_null_holm_significant_05"] else "no"])
    notes = ("Difference = first minus second model in percentage points on the 800 shared prompts; "
             "50,000-replicate dataset-stratified paired prompt-cluster bootstrap. The bootstrap-tail convention "
             "is the preregistered one; the recentered-null convention is a labeled post-hoc sensitivity. Holm "
             "correction spans all 15 pairs. Values of 0.0003 sit at the $15 \\times 1/50{,}000$ resolution floor "
             "and are upper bounds.")
    return table("table*", "@{}lrlrcrc@{}",
                 "Pair & $\\Delta$ (pp) & 95\\% CI & Holm $p$ (tail) & sig. & Holm $p$ (recent.) & sig.",
                 rows, "Track B paired comparisons under both bootstrap conventions.", "tab:paired",
                 size="\\footnotesize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 6: name-category composition and single-registry rates.
# ----------------------------------------------------------------------------------
def build_categories():
    r = load("campaign4_results.json")["track_b"]
    rows = []
    for m in TRACK_B:
        c = r[m]
        cat = c["categories"]
        total = sum(cat.values())
        rows.append([NAMES[m], num(total), f"{100 * cat['valid_both'] / total:.1f}",
                     f"{100 * cat['stdlib_mention'] / total:.1f}", num(cat["post_snapshot_package"]),
                     num(cat["deleted_since_snapshot"]), num(cat["hallucinated_both"]),
                     f"{c['rate_frozen']['rate_pct']:.2f}", f"{c['rate_current']['rate_pct']:.2f}",
                     f"{c['rate_unregistered_pypi_pct']:.2f}"])
    notes = ("Categories partition all Parser~v2-accepted occurrences. Stdlib = standard-library module named "
             "as an installable package. Post-snapshot = registered on PyPI after 2024-01-10; deleted = present in "
             "the frozen list but absent from the 2026-08-12 snapshot. Frozen-only and current-only rates score "
             "absence from a single snapshot with no stdlib exclusion; the current-only column is inflated because "
             "squat-registrations of stdlib names present in 2024 have since been purged. The primary rate requires "
             "absence from both snapshots and non-stdlib status.")
    return table("table*", "@{}lrrrrrrrrr@{}",
                 "Model & Occurrences & Valid both (\\%) & Stdlib (\\%) & Post-snap. & Deleted & Unreg.\\ both & Frozen-only (\\%) & Current-only (\\%) & Primary (\\%)",
                 rows, "Name-category composition by model and the effect of registry choice.",
                 "tab:categories", size="\\scriptsize", notes=notes)


# ----------------------------------------------------------------------------------
# Table 7: Churilov bridge (nine cells).
# ----------------------------------------------------------------------------------
def build_bridge():
    b = load("churilov_bridge_analysis.json")
    cb = b["code_bridge"]
    rows = []
    for m in ALL9:
        c = cb[m]
        rows.append([NAMES[m], num(c["extracted_mentions"]),
                     f"{100 * c['channel_mentions'].get('import', 0) / c['extracted_mentions']:.1f}",
                     f"{c['churilov_compatible_frozen_absence_rate_pct']:.2f}",
                     ci(c["churilov_compatible_frozen_cluster_ci"]),
                     f"{c['dual_registry_nonstdlib_unregistered_rate_pct']:.2f}",
                     ci(c["dual_registry_nonstdlib_cluster_ci"]), f"{c['reference_coverage_pct']:.1f}",
                     f"{c['prompt_risk_pct']:.1f}", num(c["unique_dual_registry_nonstdlib_names"])])
    s = b["bridge_summary"]
    notes = ("Churilov's public extraction design (a \\texttt{pip install} regex plus top-level imports, "
             "AST-first with a tree-sitter fallback, stdlib-list 3.11 exclusion, and the artifact's false-positive "
             "filter) applied to the frozen generated code of every cell; no responses were regenerated. Mentions "
             "are the unit of the rate; intervals cluster by prompt and stratify by dataset (50,000 replicates). "
             f"Across all nine cells, {s['total_frozen_absence_mentions']} frozen-absence mentions reduce to "
             f"{s['total_dual_registry_nonstdlib_mentions']} under the dual-registry/non-stdlib definition "
             f"({s['removed_by_current_registry_or_stdlib']} removed), and imports supply "
             f"{s['import_share_of_dual_flags_pct']:.1f}\\% of dual-registry flags. Coverage = share of prompts with "
             "any extracted reference. Churilov's reported Python range is 5.49--7.27\\%.")
    return table("table*", "@{}lrrrlrlrrr@{}",
                 "Model & Mentions & Imports (\\%) & Frozen rate (\\%) & 95\\% CI & Dual rate (\\%) & 95\\% CI & Cov.\\ (\\%) & Risk (\\%) & Unique",
                 rows, "Code-import bridge: frozen Campaign 4 and extension outputs rescored with Churilov's extractor.",
                 "tab:bridge", size="\\scriptsize", notes=notes)


def build_bridge_datasets():
    b = load("churilov_bridge_analysis.json")["code_bridge"]
    rows = []
    for m in ALL9:
        d = b[m]["by_dataset"]
        rows.append([NAMES[m]] + [f"{d[k]['dual_registry_nonstdlib_rate_pct']:.2f} ({d[k]['mentions']})"
                                  for k in ("LLM_Recent", "LLM_All_Time", "Stack_Overflow_Recent",
                                            "Stack_Overflow_All_Time")])
    notes = ("Dual-registry, non-stdlib rate in percent with the mention count in parentheses. "
             "LLM = LLM-synthesized prompts; SO = Stack Overflow prompts; LY/AT = last-year/all-time.")
    return table("table", "@{}lrrrr@{}", "Model & LLM-LY & LLM-AT & SO-LY & SO-AT", rows,
                 "Code-import bridge rates by prompt dataset.", "tab:bridgedatasets",
                 size="\\footnotesize", notes=notes, placement="H")


# ----------------------------------------------------------------------------------
# Table 8: prompt-conditioned overlap (six-cell and nine-cell summaries, six-cell pairs).
# ----------------------------------------------------------------------------------
def build_overlap():
    with open(SIX_CELL_BRIDGE, encoding="utf-8") as handle:
        six = json.load(handle)["prompt_conditioned_overlap"]
    nine = load("churilov_bridge_analysis.json")["prompt_conditioned_overlap"]
    rows = [
        ["Mean pairwise ordinary name Jaccard", f"{six['mean_pairwise_name_jaccard']:.3f}",
         f"{nine['mean_pairwise_name_jaccard']:.3f}"],
        ["Names emitted by every model", str(six["all_model_universal_name_count"]),
         str(nine["all_model_universal_name_count"])],
        ["\\quad of which emitted by every model on one identical prompt",
         str(six["all_model_same_prompt_universal_name_count"]),
         str(nine["all_model_same_prompt_universal_name_count"])],
        ["\\quad same-prompt share of the universal set (\\%)",
         f"{six['same_prompt_share_of_universal_names_pct']:.0f}",
         f"{nine['same_prompt_share_of_universal_names_pct']:.0f}"],
    ]
    notes = ("Base set: dual-registry, non-stdlib unregistered recommendations accepted by Parser~v2. "
             "The six-cell column is the frozen Campaign~4 cohort (artifact at commit \\texttt{eac1434}); "
             "the nine-cell column adds the three extension cells. Candidate names are withheld.")
    summary = table("table", "@{}p{5.6cm}rr@{}", "Overlap statistic & Six cells & Nine cells", rows,
                    "Ordinary versus prompt-aligned cross-model overlap.", "tab:overlap",
                    size="\\footnotesize", notes=notes)
    pair_rows = []
    for c in six["pairwise"]:
        pair_rows.append([pair_label(c["pair"]), str(c["shared_unique_names"]), f"{c['name_jaccard']:.3f}",
                          str(c["shared_names_with_same_prompt_support"]),
                          f"{c['same_prompt_share_of_shared_names_pct']:.0f}",
                          f"{c['prompt_aligned_occurrence_jaccard']:.3f}"])
    notes2 = ("Shared = unique unregistered names emitted by both models; same-prompt = shared names emitted "
              "by both on at least one identical prompt; aligned Jaccard is computed over "
              "(normalized name, dataset, prompt index) tuples.")
    pairs = table("table", "@{}lrrrrr@{}",
                  "Pair & Shared & Name Jaccard & Same-prompt & Share (\\%) & Aligned Jaccard", pair_rows,
                  "Pairwise overlap among the six Campaign 4 cells.", "tab:overlappairs",
                  size="\\footnotesize", notes=notes2, placement="H")
    return summary, pairs


# ----------------------------------------------------------------------------------
# Table 9: Qwen / Kimi K2.7 extension outcomes.
# ----------------------------------------------------------------------------------
def build_extension():
    res = load("ollama_cloud_extension_results.json")
    post = load("ollama_cloud_extension_post_analysis.json")["cells"]
    man = res["manifests"]
    cols = []
    for m in ("qwen3.5:cloud", "kimi-k2.7-code:cloud"):
        r, p = res["new_cells"][m], post[m]
        q1, q2 = p["by_query"]["query_1"], p["by_query"]["query_2"]
        vs = p["volume_sensitivity"]["overall"]
        cols.append({
            "Unregistered recommendation rate (\\%)": f"{r['unregistered_rate_pct']:.2f}",
            "\\quad 95\\% prompt-cluster interval": ci(r["unregistered_rate_cluster_ci"]),
            "Prompt risk (\\%)": f"{r['prompt_risk_pct']:.2f}",
            "Malformed / empty responses (\\%)": f"{r['malformed_rate_pct']:.2f} / {r['empty_rate_pct']:.2f}",
            "Parsed package occurrences": num(r["parsed_package_occurrences"]),
            "Unregistered occurrences": num(r["unregistered_occurrences"]),
            "Unique unregistered names": num(load("churilov_bridge_analysis.json")["prompt_conditioned_overlap"]["model_unique_name_counts"][m]),
            "Cap hits: code / package responses": f"{sum(p['recorded_code_response_cap_hits'].values())} / {sum(p['recorded_package_response_cap_hits'].values())}",
            "Query 1 rate (\\%) / occurrences": f"{q1['unregistered_rate_pct']:.2f} / {num(q1['parsed_package_occurrences'])}",
            "Query 2 rate (\\%) / occurrences": f"{q2['unregistered_rate_pct']:.2f} / {num(q2['parsed_package_occurrences'])}",
            "Responses with $\\leq 10$ packages: rate (\\%)": f"{vs['packages_le_10']['unregistered_rate_pct']:.2f}",
            "Responses with $> 25$ packages: rate (\\%) / occurrences":
                (f"{vs['packages_gt_25']['unregistered_rate_pct']:.2f} / {num(vs['packages_gt_25']['parsed_package_occurrences'])}"
                 if vs["packages_gt_25"]["unregistered_rate_pct"] is not None else "-- / 0"),
            "Response-macro mean / median (\\%)": f"{p['overall']['macro_rates']['response_mean_pct']:.2f} / {p['overall']['macro_rates']['response_median_pct']:.2f}",
            "Prompt-macro mean / median (\\%)": f"{p['overall']['macro_rates']['prompt_mean_pct']:.2f} / {p['overall']['macro_rates']['prompt_median_pct']:.2f}",
            "Top-3 response share (\\%)": f"{r['tail']['top3_response_share_pct']:.1f}",
            "Cap-proxy-excluded rate (\\%) [post hoc]":
                f"{p['cap_proxy_excluded']['unregistered_rate_pct']:.2f}" if p["cap_proxy_excluded"].get("unregistered_rate_pct") is not None else "n/a (no cap hits)",
            "Tokens: prompt / completion": f"{num(man[m]['token_usage_cumulative']['prompt_tokens'])} / {num(man[m]['token_usage_cumulative']['completion_tokens'])}",
        })
    rows = [[k, cols[0][k], cols[1][k]] for k in cols[0]]
    notes = ("Both cells: the Campaign~4 fixed 800-prompt subset, Parser~v2, dual registries, caps 4096/2048, "
             "\\texttt{think:false}, 2,400 calls each with zero request errors. The cap proxy is the frozen "
             "within-phase longest-response proxy because the first extension runner retained cap counts only at "
             "phase level; it is explicitly post hoc.")
    return table("table", "@{}p{4.3cm}>{\\raggedleft\\arraybackslash}p{1.6cm}>{\\raggedleft\\arraybackslash}p{2.1cm}@{}", "Outcome & Qwen 3.5 Cloud & Kimi K2.7 Code", rows,
                 "Preregistered Qwen 3.5 / Kimi K2.7 extension outcomes with query volume and cap sensitivity.",
                 "tab:extension", size="\\footnotesize", notes=notes)


def build_ext_pairs():
    ps = load("ollama_cloud_extension_results.json")["paired_comparisons"]
    rows = []
    for c in sorted(ps, key=lambda c: c["bootstrap_tail_holm_p"]):
        rows.append([pair_label(c["pair"]), f"{c['observed_diff_pp']:.2f}", ci(c["percentile_ci"]),
                     pfloor(c["bootstrap_tail_holm_p"], 13 / 50000), "yes" if c["bootstrap_tail_holm_significant_05"] else "no",
                     pfloor(c["recentered_null_holm_p"], 13 / 50000), "yes" if c["recentered_null_holm_significant_05"] else "no"])
    notes = ("Thirteen comparisons involving a new cell form their own Holm family; Campaign~4's original "
             "15-pair family is untouched. Values at the $13 \\times 1/50{,}000 = 0.00026$ floor are bounds.")
    return table("table", "@{}lrlrcrc@{}",
                 "Pair & $\\Delta$ (pp) & 95\\% CI & Holm $p$ (tail) & sig. & Holm $p$ (recent.) & sig.", rows,
                 "Paired comparisons involving the Qwen 3.5 and Kimi K2.7 extension cells.", "tab:extpairs",
                 size="\\footnotesize", notes=notes, placement="H")


# ----------------------------------------------------------------------------------
# Table 10: Kimi K3 outcomes and metadata gate.
# ----------------------------------------------------------------------------------
def build_k3():
    d = load("kimi_k3_extension_results.json")
    p = d["primary"]
    m = d["prespecified_mechanism_diagnostics"]
    q1, q2 = m["by_query"]["query_1"], m["by_query"]["query_2"]
    e = d["exact_package_cap_diagnostics"]
    g = d["response_metadata_gate"]
    vs = m["volume_sensitivity"]["overall"]
    rows = [
        ["Combined unregistered recommendation rate (\\%)", f"{p['unregistered_rate_pct']:.2f}"],
        ["\\quad 95\\% prompt-cluster interval", ci(p["unregistered_rate_cluster_ci"])],
        ["Prompt risk (\\%)", f"{p['prompt_risk_pct']:.2f}"],
        ["List coverage / malformed / empty (\\%)", f"{p['coverage_list_pct']:.2f} / {p['malformed_rate_pct']:.2f} / {p['empty_rate_pct']:.2f}"],
        ["Parsed / unregistered occurrences", f"{num(p['parsed_package_occurrences'])} / {num(p['unregistered_occurrences'])}"],
        ["Response-macro mean / prompt-macro mean (\\%)",
         f"{m['overall_response_and_volume_summary']['macro_rates']['response_mean_pct']:.2f} / {m['overall_response_and_volume_summary']['macro_rates']['prompt_mean_pct']:.2f}"],
        ["Query 1 rate (\\%) / occurrences", f"{q1['unregistered_rate_pct']:.2f} / {num(q1['parsed_package_occurrences'])}"],
        ["Query 2 rate (\\%) / occurrences", f"{q2['unregistered_rate_pct']:.2f} / {num(q2['parsed_package_occurrences'])}"],
        ["Responses with $\\leq 10$ packages: rate (\\%)", f"{vs['packages_le_10']['unregistered_rate_pct']:.2f}"],
        ["Responses with $> 25$ packages: rate (\\%) / occurrences", f"{vs['packages_gt_25']['unregistered_rate_pct']:.2f} / {num(vs['packages_gt_25']['parsed_package_occurrences'])}"],
        ["Exact cap hits: all phases / package responses", f"{g['totals']['truncated']} / {e['exact_package_cap_hits']}"],
        ["Package cap hits: share of responses / parsed / unregistered (\\%)",
         f"{100 * e['exact_package_cap_hits'] / 1600:.2f} / {100 * e['cap_hit_only']['parsed_package_occurrences'] / p['parsed_package_occurrences']:.2f} / {100 * e['cap_hit_only']['unregistered_occurrences'] / p['unregistered_occurrences']:.2f}"],
        ["Rate within package cap hits (\\%)", f"{e['cap_hit_only']['unregistered_rate_pct']:.2f}"],
        ["Rate excluding package cap hits (\\%) [post hoc]", f"{e['cap_hit_excluded']['unregistered_rate_pct']:.2f}"],
        ["Top-3 / top-10 response share (\\%)", f"{p['tail']['top3_response_share_pct']:.2f} / {p['tail']['top10_response_share_pct']:.2f}"],
        ["\\midrule"],
        ["\\multicolumn{2}{@{}l}{\\textit{Response-metadata gate}}"],
        ["Ordered sidecar rows / missing", f"{num(g['totals']['rows'])} / {g['totals']['missing']}"],
        ["Served model ids", "\\texttt{kimi-k3} only"],
        ["Request errors / request adjustments", "0 / none"],
        ["Prompt / completion tokens", f"{num(g['totals']['prompt_tokens'])} / {num(g['totals']['completion_tokens'])}"],
        ["Token-derived analytic spend (smoke excluded)", f"\\${g['estimated_cost_usd_recomputed']:.6f}"],
    ]
    fmt = [r[0] if len(r) == 1 else r for r in rows]
    notes = ("Design attested as fixed before outcome inspection, but not committed before collection; provenance "
             "and completion-gate code changed during collection and before scoring. The prespecified 33.30\\% "
             "estimate remains primary; cap-hit exclusion is post-hoc conditioning on a post-treatment variable.")
    return table("table", "@{}p{5.3cm}>{\\raggedleft\\arraybackslash}p{2.8cm}@{}", "Outcome & Kimi K3", fmt,
                 "Kimi K3 successor cell: prespecified outcomes and the exact response-metadata audit.",
                 "tab:k3", size="\\footnotesize", notes=notes)


def build_k3_pairs():
    d = load("kimi_k3_extension_results.json")
    floor = d["paired_comparison_p_value_reporting"]["smallest_resolvable_holm_adjusted_p"]
    rows = []
    for c in d["paired_comparisons"]:
        rows.append([pair_label(c["pair"]), f"{c['observed_diff_pp']:.2f}", ci(c["percentile_ci"]),
                     pfloor(c["bootstrap_tail_holm_p"], floor), pfloor(c["recentered_null_holm_p"], floor)])
    notes = ("Comparator minus Kimi K3 in percentage points over all 800 shared prompts; separate "
             "eight-comparison Holm family. Values at the $8 \\times 1/50{,}000 = 0.000160$ resolution floor "
             "are reported as bounds, never as exact $p$-values.")
    return table("table", "@{}lrlrr@{}",
                 "Pair & $\\Delta$ (pp) & 95\\% CI & Holm $p$ (tail) & Holm $p$ (recent.)", rows,
                 "Paired comparisons involving Kimi K3 (all eight survive both conventions).", "tab:k3pairs",
                 size="\\footnotesize", notes=notes, placement="H")


# ----------------------------------------------------------------------------------
# Table 11: K2.7 / K3 aggregation decomposition.
# ----------------------------------------------------------------------------------
def build_k27k3():
    d = load("kimi_k2_7_vs_k3_post_analysis.json")
    k2, k3 = d["models"]["kimi_k2_7"], d["models"]["kimi_k3"]
    pq = d["paired_q2_diagnostics"]
    ct = pq["over_100_prompt_contingency"]
    div = d["kimi_k3_q2_flood_name_diversity"]
    rows = [
        ["\\multicolumn{3}{@{}l}{\\textit{Aggregate decomposition (all package responses)}}"],
        ["Occurrence-weighted rate (\\%)", f"{k2['overall']['unregistered_rate_pct']:.2f}", f"{k3['overall']['unregistered_rate_pct']:.2f}"],
        ["Prompt risk (\\%)", f"{k2['overall']['prompt_risk_pct']:.2f}", f"{k3['overall']['prompt_risk_pct']:.2f}"],
        ["Response-macro mean (\\%)", f"{k2['overall']['macro_rates']['response_mean_pct']:.2f}", f"{k3['overall']['macro_rates']['response_mean_pct']:.2f}"],
        ["Responses with $\\geq 100$ packages", num(k2["overall"]["packages_per_response"]["responses_ge_100"]), num(k3["overall"]["packages_per_response"]["responses_ge_100"])],
        ["Package cap hits (K2.7: proxy; K3: exact)", num(k2["cap_proxy_contribution"]["selected_responses"]), num(k3["exact_cap_contribution"]["selected_responses"])],
        ["\\quad share of responses / parsed / unregistered (\\%)",
         f"{k2['cap_proxy_contribution']['response_share_pct']:.1f} / {k2['cap_proxy_contribution']['occurrence_share_pct']:.1f} / {k2['cap_proxy_contribution']['unregistered_share_pct']:.1f}",
         f"{k3['exact_cap_contribution']['response_share_pct']:.1f} / {k3['exact_cap_contribution']['occurrence_share_pct']:.1f} / {k3['exact_cap_contribution']['unregistered_share_pct']:.1f}"],
        ["Rate inside the cap tail (\\%)", f"{k2['cap_proxy_only']['unregistered_rate_pct']:.2f}", f"{k3['exact_cap_only']['unregistered_rate_pct']:.2f}"],
        ["Rate excluding the cap tail (\\%) [post hoc]", f"{k2['cap_proxy_excluded']['unregistered_rate_pct']:.2f}", f"{k3['exact_cap_excluded']['unregistered_rate_pct']:.2f}"],
        ["\\midrule"],
        ["\\multicolumn{3}{@{}l}{\\textit{Shared-prompt Query 2 diagnostics (K2.7 minus K3, pp; 95\\% paired CI)}}"],
        ["Prompt risk", f"{pq['q2_prompt_risk']['k2_7_pct']:.2f}\\% vs.\\ {pq['q2_prompt_risk']['k3_pct']:.2f}\\%",
         f"{pq['q2_prompt_risk']['k2_7_minus_k3_pp']:.2f} ({ci(pq['q2_prompt_risk']['paired_prompt_cluster_bootstrap_95_ci'])})"],
        ["Responses over 100 packages", f"{pq['q2_responses_over_100_packages']['k2_7_pct']:.2f}\\% vs.\\ {pq['q2_responses_over_100_packages']['k3_pct']:.2f}\\%",
         f"{pq['q2_responses_over_100_packages']['k2_7_minus_k3_pp']:.2f} ({ci(pq['q2_responses_over_100_packages']['paired_prompt_cluster_bootstrap_95_ci'])})"],
        ["Flood contingency (both / K2.7 only / K3 only / neither)", f"{ct['both']} / {ct['k2_7_only']} / {ct['k3_only']} / {ct['neither']}", ""],
        ["Expected joint floods under independence; odds ratio", f"{ct['expected_both_under_independence']:.1f}; {ct['odds_ratio']:.2f}", ""],
        ["Flood-prompt Jaccard; maximum given marginals", f"{ct['prompt_set_jaccard']:.3f}; {ct['maximum_jaccard_given_marginals']:.3f}", ""],
        ["\\midrule"],
        ["\\multicolumn{3}{@{}l}{\\textit{K3 flood diversity (54 Query 2 responses above 100 packages)}}"],
        ["Unique normalized packages / unregistered names", f"{num(div['unique_normalized_packages'])} / {num(div['unique_normalized_unregistered'])}", ""],
        ["Mean pairwise Jaccard: package sets / unregistered sets", f"{div['package_set_jaccard']['mean']:.4f} / {div['unregistered_set_jaccard']['mean']:.4f}", ""],
        ["Unregistered names in $\\geq 25\\%$ of floods", str(div["unregistered_in_at_least_25pct_responses"]), ""],
    ]
    fmt = [r[0] if len(r) == 1 else r for r in rows]
    notes = ("K3 cap membership is exact (finish reason and token counts per response); K2.7 cap membership is "
             "the frozen within-phase longest-response proxy. Paired intervals resample prompts within each of the "
             "four 200-prompt datasets (50,000 replicates). Cap exclusion is diagnostic conditioning, not a causal "
             "estimate.")
    return table("table", "@{}p{4.0cm}>{\\raggedleft\\arraybackslash}p{2.2cm}>{\\raggedleft\\arraybackslash}p{2.0cm}@{}", "Diagnostic & Kimi K2.7 & Kimi K3", fmt,
                 "Kimi K2.7 versus Kimi K3: aggregation decomposition, shared-prompt flood contingency, and cap-tail influence.",
                 "tab:k27k3", size="\\scriptsize", notes=notes)


# ----------------------------------------------------------------------------------
# Appendix tables.
# ----------------------------------------------------------------------------------
def build_cap_cells():
    d = load("campaign4_post_analysis.json")["cap_diagnostic_paired_sensitivity"]
    rows = []
    for model, label in (("deepseek-coder-v2_16b", "DeepSeek Coder V2 16B"),
                         ("deepseek-coder_6.7b-instruct", "DeepSeek Coder 6.7B")):
        cells = d[model]["cells"]
        for i, cap in enumerate(("64", "128", "256", "512", "2048")):
            c = cells[cap]
            rows.append([label if i == 0 else "", cap, num(c["packages"]), num(c["unregistered_frozen"]),
                         f"{c['rate_pct']:.2f}", f"{c['malformed_rate_pct']:.1f}",
                         f"{c['delta_vs_2048_pp']:.2f}" if "delta_vs_2048_pp" in c else "ref.",
                         ci(c["delta_vs_2048_percentile_ci"]) if "delta_vs_2048_percentile_ci" in c else ""])
        rows.append(["\\quad Spearman $\\rho$ (rate vs.\\ cap)", "", "", "", f"{d[model]['spearman_rho_rate_vs_increasing_cap']:.2f}", "", "", ""])
    notes = ("100 prompts (25 per dataset), both package queries, temperature 0, seed 7, one worker, "
             "counterbalanced cap order, Parser~v2, frozen 2024 registry. Deltas pair each cap with the 2048-token "
             "response at the prompt level (20,000-replicate dataset-stratified bootstrap). No equivalence margin "
             "was preregistered, so a small delta is not proof of no effect.")
    return table("table", "@{}llrrrrrl@{}",
                 "Model & Cap & Packages & Unreg. & Rate (\\%) & Malformed (\\%) & $\\Delta$ vs.\\ 2048 (pp) & 95\\% CI",
                 rows, "Controlled cap diagnostic: paired cells.", "tab:capcells", size="\\footnotesize", notes=notes,
                 placement="H")


def build_cap_bands():
    d = load("campaign4_results.json")["phase2_position_bands"]
    rows = []
    for model, label in (("deepseek-coder-v2_16b", "DeepSeek Coder V2 16B"),
                         ("deepseek-coder_6.7b-instruct", "DeepSeek Coder 6.7B")):
        first = True
        for cap in ("64", "128", "256", "512", "2048"):
            for q in ("q1", "q2"):
                bands = d[model][f"cap={cap}|{q}"]
                rows.append([label if first else "", cap, q.upper()] +
                            [tex_escape(bands.get(k, "--")) for k in ("p1", "p2", "p3", "p4", "p5+")])
                first = False
    notes = ("Unregistered (frozen-registry) rate at each package position within grammar-valid responses, "
             "with the number of responses contributing at that position. Q1 = packages required by the "
             "generated code; Q2 = packages useful for the task.")
    return table("table", "@{}lllrrrrr@{}", "Model & Cap & Query & Pos.\\ 1 & Pos.\\ 2 & Pos.\\ 3 & Pos.\\ 4 & Pos.\\ 5+",
                 rows, "Controlled cap diagnostic: position-band rates.", "tab:capbands", size="\\scriptsize",
                 notes=notes, placement="H")


def build_positions():
    post = load("ollama_cloud_extension_post_analysis.json")["cells"]
    k3 = load("kimi_k3_extension_results.json")
    k27k3 = load("kimi_k2_7_vs_k3_post_analysis.json")["q2_position_rate_cap_excluded"]
    bins = ["1", "2", "3-5", "6-10", "11-25", "26-50", "51-100", "101+"]

    def prof(items):
        return {it["position"]: it for it in items}

    qwen = prof(post["qwen3.5:cloud"]["position_profile_query_2"])
    k2 = prof(post["kimi-k2.7-code:cloud"]["position_profile_query_2"])
    k2x = prof(post["kimi-k2.7-code:cloud"]["position_profile_query_2_cap_proxy_excluded"])
    k3q2 = prof(k3["prespecified_mechanism_diagnostics"]["position_profile_query_2"])
    k3x = k27k3["kimi_k3_exact_excluded"]
    rows = []
    for b in bins:
        def cell(p):
            it = p.get(b)
            if not it or it["unregistered_rate_pct"] is None:
                return "--"
            return f"{it['unregistered_rate_pct']:.2f} ({num(it['occurrences'])})"
        rows.append([b, cell(qwen), cell(k2), cell(k2x) if b in k2x else "--",
                     cell(k3q2), f"{k3x[b]:.2f}"])
    notes = ("Occurrence-weighted unregistered rate in percent with parsed occurrences in parentheses, by "
             "package position within Query~2 responses. Excluded columns remove the K2.7 longest-response cap "
             "proxy or the exact K3 package cap hits; late bins after exclusion rest on few responses and are "
             "mechanism evidence, not stable population rates.")
    return table("table", "@{}lrrrrr@{}",
                 "Position & Qwen 3.5 & Kimi K2.7 & K2.7, proxy excluded & Kimi K3 & K3, exact caps excluded",
                 rows, "Query 2 position profiles for the extension cells.", "tab:positions",
                 size="\\footnotesize", notes=notes, placement="H")


def main():
    os.makedirs(OUT, exist_ok=True)
    write("tab_cells.tex", build_cells())
    write("tab_parser.tex", build_parser())
    write("tab_tracka.tex", build_tracka())
    write("tab_trackb.tex", build_trackb())
    write("tab_paired.tex", build_paired())
    write("tab_categories.tex", build_categories())
    write("tab_bridge.tex", build_bridge())
    write("tab_bridgedatasets.tex", build_bridge_datasets())
    summary, pairs = build_overlap()
    write("tab_overlap.tex", summary)
    write("tab_overlappairs.tex", pairs)
    write("tab_extension.tex", build_extension())
    write("tab_extpairs.tex", build_ext_pairs())
    write("tab_k3.tex", build_k3())
    write("tab_k3pairs.tex", build_k3_pairs())
    write("tab_k27k3.tex", build_k27k3())
    write("tab_capcells.tex", build_cap_cells())
    write("tab_capbands.tex", build_cap_bands())
    write("tab_positions.tex", build_positions())


if __name__ == "__main__":
    sys.exit(main())
